spring.application.name=stockflow

# --- Database connection ---
# Uses env vars if set (production), otherwise falls back to your local values (development)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/stockflow}
spring.datasource.username=${DATABASE_USERNAME:postgres}
#spring.datasource.password=${DATABASE_PASSWORD:minhaj8184@}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# --- JWT ---
app.jwt.secret=${JWT_SECRET:OoQXEG5XL3jbWyDV22COBz3xZXEG1Ey/YUruUknP5tVP7rNco3woqZ4JRFVioCds}
app.jwt.expiration-ms=86400000

# --- CORS ---
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}